(()=>{
 'use strict';
 const KEY='my-minute.connection';let connection=null,reminderRequests=Promise.resolve();
 try{connection=JSON.parse(localStorage.getItem(KEY)||'null');}catch{}
 async function rawRequest(path,method='GET',data){if(!connection)throw new Error('Connect the reminder service first.');const res=await fetch(connection.url+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+connection.token},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(90000)});let body;try{body=await res.json();}catch{throw new Error('The service did not return a valid response.');}if(!res.ok)throw new Error(body.error||'Could not reach the service.');return body;}
 function request(path,method='GET',data){if(path!=='/reminders')return rawRequest(path,method,data);const pending=reminderRequests.catch(()=>{}).then(()=>rawRequest(path,method,data));reminderRequests=pending;return pending;}
 async function pair(url,code){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.search||parsed.hash)throw new Error('Enter the HTTPS address of your My Minute service.');const base=parsed.origin,res=await fetch(base+'/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code}),signal:AbortSignal.timeout(30000)}),data=await res.json();if(!res.ok)throw new Error(data.error||'Could not connect.');connection={url:base,token:data.token};localStorage.setItem(KEY,JSON.stringify(connection));return data;}
 async function subscription(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('On iPhone, add My Minute to your Home Screen and open it there to enable reminders.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications are not allowed. Enable them in your device settings.');const status=await request('/status'),registration=await navigator.serviceWorker.ready;let sub=await registration.pushManager.getSubscription();if(!sub){const bytes=Uint8Array.from(atob(status.vapidPublicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});}return sub.toJSON();}
 async function setReminders(enabled,jobs){const sub=enabled?await subscription():null;return request('/reminders','POST',{enabled,jobs,subscription:sub});}
 async function disconnect(){await request('/device','DELETE');connection=null;localStorage.removeItem(KEY);}
 window.MinuteService={connected:()=>!!connection,pair,request,setReminders,disconnect};
})();
